# Generated by Django 3.2.5 on 2021-07-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('priority', models.CharField(max_length=20)),
                ('duedate', models.DateTimeField()),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
